name: Tests
on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
jobs:
  test:
    name: Quality Gate
    # プルリクエストがdraft,release,docの時は実行しない
    if: |
      github.event.pull_request.draft == false
      && !startsWith(github.head_ref, 'release')
      && !startsWith(github.head_ref, 'doc')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build and Test with Gradle
        continue-on-error: true
        run: ./gradlew --no-daemon clean check test --fail-fast
      - name: Create annotation for build error
        run: echo "::warning file=src/main/java/com/example/demo/DemoApplication.java,line=9::Testing annotation"
      - name: Create Temporary Directory
        run: mkdir tmp
      - name: Produce Output
        id: producer_step
        run: echo "result=Test output" >> $GITHUB_OUTPUT
      - name: Consume Output
        run: echo "Output = ${{steps.producer_step.outputs.result}}"
      - name: Generate Example Table
        run: |
          touch tmp/warnings_table.txt
          echo "|Type|Detail|" >> tmp/warnings_table.txt
          echo "|--|--|" >> tmp/warnings_table.txt
          echo "|Test|テスト|" >> tmp/warnings_table.txt
          echo "Testing summary" >> $GITHUB_STEP_SUMMARY
          echo "|Type|Detail|" >> $GITHUB_STEP_SUMMARY
          echo "|--|--|" >> $GITHUB_STEP_SUMMARY
          echo "|Test|テスト|\n" >> $GITHUB_STEP_SUMMARY
      - name: Find Warning Suppressions
        run: |
          git fetch origin ${{ github.base_ref }}
          # Run the diff using three-dot or two-dot notation
          echo "\n\n:warning:New Warning Suppressions:warning:\n" >> tmp/warning_tables.txt
          git diff origin/${{ github.base_ref }}...HEAD -G "@SuppressWarning" >>  tmp/warning_tables.txt
      - name: Parse PMD result
        run: |
          echo "\n\nPMD\n" >> tmp/warnings_table.txt
          echo "|Type|Message|Location|" >> tmp/warnings_table.txt
          echo "|--|--|--|" >> tmp/warnings_table.txt
          jq -r '"|" + .runs[].results[] | .ruleId + "|" + .message.text + "|" + .locations[0].physicalLocation.artifactLocation.uri + ":" + (.locations[0].physicalLocation.region.startLine | tostring) + "-" + (.locations[0].physicalLocation.region.endLine | tostring) + "|\n"' build/reports/pmd/main.sarif.json >> tmp/warnings_table.txt
          [ "$(jq '.runs[0].results | length' build/reports/pmd/main.sarif.json)" -ne 0 ] && exit 1
      - name: Comment PR
        if: always()
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: tmp/warnings_table.txt
          comment-tag: warnings_table
