name: Tests
on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
jobs:
  test:
    name: Run Test Code
    # プルリクエストがdraft,release,docの時は実行しない
    if: |
      github.event.pull_request.draft == false
      && !startsWith(github.head_ref, 'release')
      && !startsWith(github.head_ref, 'doc')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
#      - name: Setup Java
#        uses: actions/setup-java@v5
#        with:
#          distribution: 'temurin'
#          java-version: 25
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v5
#      - name: Build and Test with Gradle
#        run: ./gradlew --no-daemon clean check test --fail-fast
      - name: Create annotation for build error
        run: echo "::warning file=src/DemoApplication.java,line=9::Testing annotation"
      - name: Create Temporary Directory
        run: mkdir tmp
      - name: Generate Example Table
        run: |
          touch tmp/warnings_table.txt
          echo "|Type|Detail|" >> tmp/warnings_table.txt
          echo "|--|--|" >> tmp/warnings_table.txt
          echo "|Test|テスト|" >> tmp/warnings_table.txt
          echo "Testing summary" >> $GITHUB_STEP_SUMMARY
          echo "|Type|Detail|" >> $GITHUB_STEP_SUMMARY
          echo "|--|--|" >> $GITHUB_STEP_SUMMARY
          echo "|Test|テスト|" >> $GITHUB_STEP_SUMMARY
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: tmp/warnings_table.txt
          comment-tag: warnings_table
